import type { RegistryEntry } from "../../shared.ts";

const META_OAUTH_CLIENT_ID = process.env.META_OAUTH_CLIENT_ID?.trim() || "1031625952748946";
const MUSE_THINKING_EFFORTS = ["minimal", "low", "medium", "high", "xhigh"];

/**
 * Meta Model API / Muse Code.
 *
 * OAuth uses Meta's OIDC device flow. The resulting identity token is exchanged
 * for a Model API key and that key is sent as the Bearer credential to api.meta.ai.
 * Direct API-key connections remain supported through the dashboard's dual-auth path.
 */
export const muse_codeProvider: RegistryEntry = {
  id: "muse-code",
  alias: "mc",
  format: "openai",
  executor: "default",
  baseUrl: "https://api.meta.ai/v1/chat/completions",
  responsesBaseUrl: "https://api.meta.ai/v1/responses",
  authType: "oauth",
  authHeader: "bearer",
  passthroughModels: true,
  reasoningTransport: "opaque",
  defaultContextLength: 1_048_576,
  oauth: {
    clientIdEnv: "META_OAUTH_CLIENT_ID",
    clientIdDefault: META_OAUTH_CLIENT_ID,
    tokenUrl: "https://auth.meta.com/oidc/device/token/",
    authUrl: "https://auth.meta.com",
  },
  models: [
    {
      id: "muse-spark-1.3",
      name: "Muse Spark 1.3",
      contextLength: 1_048_576,
      maxOutputTokens: 256_000,
      supportsReasoning: true,
      supportedThinkingEfforts: MUSE_THINKING_EFFORTS,
      supportsXHighEffort: true,
      toolCalling: true,
      supportsVision: true,
      targetFormat: "openai-responses",
      unsupportedParams: ["logprobs", "topLogprobs", "logitBias"],
    },
    {
      id: "muse-spark-1.3-contributor",
      name: "Muse Spark 1.3 Contributor",
      contextLength: 1_048_576,
      maxOutputTokens: 256_000,
      supportsReasoning: true,
      supportedThinkingEfforts: MUSE_THINKING_EFFORTS,
      supportsXHighEffort: true,
      toolCalling: true,
      supportsVision: true,
      targetFormat: "openai-responses",
      unsupportedParams: ["logprobs", "topLogprobs", "logitBias"],
    },
    {
      id: "muse-spark-1.2",
      name: "Muse Spark 1.2",
      contextLength: 1_048_576,
      maxOutputTokens: 256_000,
      supportsReasoning: true,
      supportedThinkingEfforts: MUSE_THINKING_EFFORTS,
      supportsXHighEffort: true,
      toolCalling: true,
      supportsVision: true,
      targetFormat: "openai-responses",
      unsupportedParams: ["logprobs", "topLogprobs", "logitBias"],
    },
    {
      id: "muse-spark-1.2-contributor",
      name: "Muse Spark 1.2 Contributor",
      contextLength: 1_048_576,
      maxOutputTokens: 256_000,
      supportsReasoning: true,
      supportedThinkingEfforts: MUSE_THINKING_EFFORTS,
      supportsXHighEffort: true,
      toolCalling: true,
      supportsVision: true,
      targetFormat: "openai-responses",
      unsupportedParams: ["logprobs", "topLogprobs", "logitBias"],
    },
    {
      id: "muse-spark-1.1",
      name: "Muse Spark 1.1",
      contextLength: 1_048_576,
      maxOutputTokens: 256_000,
      supportsReasoning: true,
      supportedThinkingEfforts: MUSE_THINKING_EFFORTS,
      supportsXHighEffort: true,
      toolCalling: true,
      supportsVision: true,
      targetFormat: "openai-responses",
      unsupportedParams: ["logprobs", "topLogprobs", "logitBias"],
    },
    {
      id: "llama-4-maverick",
      name: "Llama 4 Maverick",
      contextLength: 1_048_576,
      maxOutputTokens: 131_072,
      supportsReasoning: true,
      supportsXHighEffort: true,
      toolCalling: true,
      supportsVision: true,
      targetFormat: "openai-responses",
      unsupportedParams: ["logprobs", "topLogprobs", "logitBias"],
    },
    {
      id: "llama-4-scout",
      name: "Llama 4 Scout",
      contextLength: 1_048_576,
      maxOutputTokens: 131_072,
      supportsReasoning: true,
      supportsXHighEffort: true,
      toolCalling: true,
      supportsVision: true,
      targetFormat: "openai-responses",
      unsupportedParams: ["logprobs", "topLogprobs", "logitBias"],
    },
    {
      id: "llama-3.3-70b",
      name: "Llama 3.3 70B",
      contextLength: 131_072,
      maxOutputTokens: 32_768,
      supportsReasoning: false,
      toolCalling: true,
      targetFormat: "openai-responses",
      unsupportedParams: ["logprobs", "topLogprobs"],
    },
    {
      id: "llama-3.1-405b",
      name: "Llama 3.1 405B",
      contextLength: 131_072,
      maxOutputTokens: 32_768,
      supportsReasoning: false,
      toolCalling: true,
      targetFormat: "openai-responses",
      unsupportedParams: ["logprobs", "topLogprobs"],
    },
    {
      id: "llama-3.1-70b",
      name: "Llama 3.1 70B",
      contextLength: 131_072,
      maxOutputTokens: 32_768,
      supportsReasoning: false,
      toolCalling: true,
      targetFormat: "openai-responses",
      unsupportedParams: ["logprobs", "topLogprobs"],
    },
    {
      id: "llama-3.1-8b",
      name: "Llama 3.1 8B",
      contextLength: 131_072,
      maxOutputTokens: 32_768,
      supportsReasoning: false,
      toolCalling: true,
      targetFormat: "openai-responses",
      unsupportedParams: ["logprobs", "topLogprobs"],
    },
    {
      id: "llama-3.2-90b-vision",
      name: "Llama 3.2 90B Vision",
      contextLength: 131_072,
      maxOutputTokens: 32_768,
      supportsReasoning: false,
      toolCalling: true,
      supportsVision: true,
      targetFormat: "openai-responses",
      unsupportedParams: ["logprobs", "topLogprobs"],
    },
    {
      id: "llama-3.2-11b-vision",
      name: "Llama 3.2 11B Vision",
      contextLength: 131_072,
      maxOutputTokens: 32_768,
      supportsReasoning: false,
      toolCalling: true,
      supportsVision: true,
      targetFormat: "openai-responses",
      unsupportedParams: ["logprobs", "topLogprobs"],
    },
  ],
};
